environment: development
#environment: production

version: V01
calculations:
  V01:
    - RetailerAlphanumeric
    - TotalRoundDollar
    - TotalMultipleQuarter
    - ItemPairs
    - ItemDesc
    - OddPurchaseDate
    - AfternoonPurchaseTime