version: V01

#environment: development
environment: production

calculations:
  V01:
    - RetailerAlphanumeric
    - TotalRoundDollar
    - TotalMultipleQuarter
    - ItemPairs
    - ItemDesc
    - OddPurchaseDate
    - AfternoonPurchaseTime

test:
  version: v01
  path: Tests/TestCases
